//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTrustUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_apps
    {
        public int id { get; set; }
        public string client_id { get; set; }
        public string client_secret { get; set; }
        public string kdt_id { get; set; }
        public string appname { get; set; }
        public Nullable<System.DateTime> expireddate { get; set; }
        public string status { get; set; }
        public string appcode { get; set; }
        public string homeurl { get; set; }
    }
}
