//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTrustUs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_giftcard
    {
        public int id { get; set; }
        public string giftcardcode { get; set; }
        public Nullable<int> PromoId { get; set; }
        public string generatedate { get; set; }
        public string isused { get; set; }
        public string useddate { get; set; }
        public string forcompany { get; set; }
        public string expireddate { get; set; }
        public string usedopenid { get; set; }
        public string usedmobile { get; set; }
        public string usedname { get; set; }
        public string amount { get; set; }
        public string enabled { get; set; }
        public string jumpurl { get; set; }
        public string isusedt { get; set; }
        public string enabledt { get; set; }
    }
}
